/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.workflow.InterfacesGraficas;

import javax.swing.JOptionPane;

import com.mycompany.workflow.Encriptacion.Encriptacion;
import com.mycompany.workflow.Encriptacion.VerificacionLogueo;
import com.mycompany.workflow.EstructuraUsuarios.Usuario;

/**
 *
 * @author danielpaput
 */
public class ReistroForm extends javax.swing.JFrame {

    VerificacionLogueo verifLog = new VerificacionLogueo();
    Usuario user = new Usuario();
    /**
     * Creates new form ReistroForm
     */
    public ReistroForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textFieldCorreoElectronico = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        passwordFieldContraseña1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        passwordFieldContraseña2 = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        buttonRegistrarse = new javax.swing.JButton();
        buttonRegresarLogueo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(112, 145, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONTRASEÑA:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 440, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INICIO DE SESIÓN");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        textFieldCorreoElectronico.setBackground(new java.awt.Color(112, 145, 255));
        textFieldCorreoElectronico.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        textFieldCorreoElectronico.setForeground(new java.awt.Color(255, 255, 255));
        textFieldCorreoElectronico.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldCorreoElectronico.setBorder(null);
        textFieldCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCorreoElectronicoActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 260, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 250, 310, 10));
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CORREO ELECTRÓNICO:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 200, -1, -1));

        passwordFieldContraseña1.setBackground(new java.awt.Color(112, 145, 255));
        passwordFieldContraseña1.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        passwordFieldContraseña1.setForeground(new java.awt.Color(255, 255, 255));
        passwordFieldContraseña1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordFieldContraseña1.setBorder(null);
        passwordFieldContraseña1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        passwordFieldContraseña1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldContraseña1ActionPerformed(evt);
            }
        });
        jPanel1.add(passwordFieldContraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 260, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 340, 310, 10));
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        passwordFieldContraseña2.setBackground(new java.awt.Color(112, 145, 255));
        passwordFieldContraseña2.setFont(new java.awt.Font("Lucida Sans", 1, 12)); // NOI18N
        passwordFieldContraseña2.setForeground(new java.awt.Color(255, 255, 255));
        passwordFieldContraseña2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passwordFieldContraseña2.setBorder(null);
        passwordFieldContraseña2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(passwordFieldContraseña2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 400, 260, -1));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        buttonRegistrarse.setBackground(new java.awt.Color(81, 84, 255));
        buttonRegistrarse.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        buttonRegistrarse.setForeground(new java.awt.Color(255, 255, 255));
        buttonRegistrarse.setText("Iniciar Sesión");
        buttonRegistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 360, -1, 40));

        buttonRegresarLogueo.setBackground(new java.awt.Color(112, 145, 255));
        buttonRegresarLogueo.setForeground(new java.awt.Color(112, 145, 255));
        buttonRegresarLogueo.setBorder(null);
        buttonRegresarLogueo.setBorderPainted(false);
        buttonRegresarLogueo.setContentAreaFilled(false);
        buttonRegresarLogueo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegresarLogueoActionPerformed(evt);
            }
        });
        jPanel1.add(buttonRegresarLogueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/workflow/InterfacesGraficas/userInicio.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 55, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/workflow/InterfacesGraficas/key.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/workflow/InterfacesGraficas/userLabel.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCorreoElectronicoActionPerformed

    private void buttonRegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegistrarseActionPerformed
        // TODO add your handling code here:
        //valirdarRegistro(textFieldCorreoElectronico, passwordFieldContraseña2, passwordFieldContraseña1);
        validar();
    }//GEN-LAST:event_buttonRegistrarseActionPerformed

    private void buttonRegresarLogueoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegresarLogueoActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(null,"Hola, esta ventana simula el regreso al Logueo");
    }//GEN-LAST:event_buttonRegresarLogueoActionPerformed

    private void passwordFieldContraseña1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldContraseña1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldContraseña1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReistroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReistroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReistroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReistroForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReistroForm().setVisible(true);
            }
        });
    }

    public void validar () {
        String correo = textFieldCorreoElectronico.getText();
        String pass = String.valueOf(passwordFieldContraseña1.getPassword());

        Encriptacion encriptacion = new Encriptacion();
        String passEncriptada = encriptacion.encryptPassword(pass);
        

        if (!"".equals(correo) || !"".equals(pass)) {
            user = verifLog.user(correo, passEncriptada);
            if (user.getMail()!=null && user.getPasswordS()!=null) {
                if (encriptacion.checkPassword(pass, user.getPasswordS())) {
                    System.out.println("EXITO");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Correo o contraseña incorrecta");
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonRegistrarse;
    private javax.swing.JButton buttonRegresarLogueo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField passwordFieldContraseña1;
    private javax.swing.JPasswordField passwordFieldContraseña2;
    private javax.swing.JTextField textFieldCorreoElectronico;
    // End of variables declaration//GEN-END:variables
}
